In [24]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [25]:
df=pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,60,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,35,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,55,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,56,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [26]:
df.shape

(289, 14)

In [27]:
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [31]:
df.drop(['oldpeak','slp','caa','thall'],axis=1,inplace=True)
df.head()

   age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  output
0   60    1   3     145   233    1        0       150     0       1
1   35    1   2     130   250    0        1       187     0       1
2   41    0   1     130   204    0        0       172     0       1
3   55    1   1     120   236    0        1       178     0       1
4   56    0   0     120   354    0        1       163     1       1

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       289 non-null    int64
 1   sex       289 non-null    int64
 2   cp        289 non-null    int64
 3   trtbps    289 non-null    int64
 4   chol      289 non-null    int64
 5   fbs       289 non-null    int64
 6   restecg   289 non-null    int64
 7   thalachh  289 non-null    int64
 8   exng      289 non-null    int64
 9   output    289 non-null    int64
dtypes: int64(10)
memory usage: 22.7 KB

In [33]:
df.describe()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,output
count,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000
mean,54.010381,0.678201,1.020761,131.377163,247.961938,0.145329,0.515571,150.231834,0.318339,0.570934
std,9.132316,0.467977,1.027192,17.518432,51.596208,0.353043,0.514309,22.899650,0.466640,0.495801
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000
25%,47.000000,0.000000,0.000000,120.000000,212.000000,0.000000,0.000000,136.000000,0.000000,0.000000
50%,54.000000,1.000000,1.000000,130.000000,243.000000,0.000000,1.000000,154.000000,0.000000,1.000000
75%,60.000000,1.000000,2.000000,140.000000,276.000000,0.000000,1.000000,168.000000,1.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,1.000000

In [10]:
%pip install pgmpy

Collecting pgmpy
  Downloading pgmpy-1.1.2-py3-none-any.whl.metadata (13 kB)
Collecting huggingface_hub>=0.23 (from pgmpy)
  Downloading huggingface_hub-1.32.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: networkx>=3.0 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (3.5)
Requirement already satisfied: numpy>=2.0 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (2.3.5)
Requirement already satisfied: scipy>=1.10 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (1.16.3)
Requirement already satisfied: scikit-learn>=1.2 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (1.7.2)
Requirement already satisfied: pandas>=1.5 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (2.3.3)
Requirement already satisfied: statsmodels>=0.14.5 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (0.14.5)
Requirement already satisfied: tqdm>=4.64 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (4.67.1)
Requirement already satisfied: pyparsing>=3.0 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (3.2.5)
Requirement already satisfied: joblib>=1.2 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (1.5.2)
Requirement already satisfied: opt_einsum>=3.3 in c:\users\harini.c\anaconda3\lib\site-packages (from pgmpy) (3.4.0)
Collecting scikit-base>=0.12.4 (from pgmpy)
  Downloading scikit_base-1.1.1-py3-none-any.whl.metadata (8.8 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface_hub>=0.23->pgmpy)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\harini.c\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\harini.c\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (2025.10.0)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface_hub>=0.23->pgmpy)
  Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\harini.c\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\harini.c\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\harini.c\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (6.0.3)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\harini.c\anaconda3\lib\site-packages (from huggingface_hub>=0.23->pgmpy) (4.15.0)
Requirement already satisfied: anyio in c:\users\harini.c\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (4.10.0)
Requirement already satisfied: certifi in c:\users\harini.c\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\harini.c\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (1.0.9)
Requirement already satisfied: idna in c:\users\harini.c\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\harini.c\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\harini.c\anaconda3\lib\site-packages (from pandas>=1.5->pgmpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\harini.c\anaconda3\lib\site-packages (from pandas>=1.5->pgmpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\harini.c\anaconda3\lib\site-packages (from pandas>=1.5->pgmpy) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\harini.c\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5->pgmpy) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\harini.c\anaconda3\lib\site-packages (from scikit-learn>=1.2->pgmpy) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\harini.c\anaconda3\lib\site-packages (from statsmodels>=0.14.5->pgmpy) (1.0.1)
Requirement already satisfied: colorama in c:\users\harini.c\anaconda3\lib\site-packages (from tqdm>=4.64->pgmpy) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\harini.c\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.23->pgmpy) (1.3.0)
Downloading pgmpy-1.1.2-py3-none-any.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 771.8 kB/s eta 0:00:03
   ------------ --------------------------- 0.8/2.4 MB 844.7 kB/s eta 0:00:02
   ----------------- ---------------------- 1.0/2.4 MB 937.5 kB/s eta 0:00:02
   --------------------- ------------------ 1.3/2.4 MB 1.1 MB/s eta 0:00:02
   ------------------------------ --------- 1.8/2.4 MB 1.2 MB/s eta 0:00:01
   ------------------------------ --------- 1.8/2.4 MB 1.2 MB/s eta 0:00:01
   -------------------------------------- - 2.4/2.4 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 1.1 MB/s  0:00:02
Downloading huggingface_hub-1.32.0-py3-none-any.whl (842 kB)
   ---------------------------------------- 0.0/842.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/842.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/842.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/842.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/842.9 kB ? eta -:--:--
   ------------ --------------------------- 262.1/842.9 kB ? eta -:--:--
   ------------------------ --------------- 524.3/842.9 kB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 842.9/842.9 kB 1.2 MB/s  0:00:01
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 2.0 MB/s eta 0:00:02
   ---------- ----------------------------- 1.0/4.0 MB 1.7 MB/s eta 0:00:02
   ------------ --------------------------- 1.3/4.0 MB 1.8 MB/s eta 0:00:02
   --------------- ------------------------ 1.6/4.0 MB 1.6 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.0 MB 1.5 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.0 MB 1.5 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.4 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.4 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.2 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.2 MB/s eta 0:00:02
   ------------------------- -------------- 2.6/4.0 MB 965.6 kB/s eta 0:00:02
   ------------------------- -------------- 2.6/4.0 MB 965.6 kB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 891.0 kB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 891.0 kB/s eta 0:00:02
   ------------------------------- -------- 3.1/4.0 MB 854.2 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 904.0 kB/s eta 0:00:01
   -------------------------------------- - 3.9/4.0 MB 981.6 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 974.7 kB/s  0:00:04
Downloading scikit_base-1.1.1-py3-none-any.whl (162 kB)
Installing collected packages: scikit-base, hf-xet, click, huggingface_hub, pgmpy

   ---------------------------------------- 0/5 [scikit-base]
   ---------------------------------------- 0/5 [scikit-base]
   ---------------------------------------- 0/5 [scikit-base]
   ---------------------------------------- 0/5 [scikit-base]
   ---------------------------------------- 0/5 [scikit-base]
   -------- ------------------------------- 1/5 [hf-xet]
  Attempting uninstall: click
   -------- ------------------------------- 1/5 [hf-xet]
    Found existing installation: click 8.2.1
   -------- ------------------------------- 1/5 [hf-xet]
    Uninstalling click-8.2.1:
   -------- ------------------------------- 1/5 [hf-xet]
      Successfully uninstalled click-8.2.1
   -------- ------------------------------- 1/5 [hf-xet]
   ---------------- ----------------------- 2/5 [click]
   ---------------- ----------------------- 2/5 [click]
   ---------------- ----------------------- 2/5 [click]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   ------------------------ --------------- 3/5 [huggingface_hub]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   -------------------------------- ------- 4/5 [pgmpy]
   ---------------------------------------- 5/5 [pgmpy]

Successfully installed click-8.5.0 hf-xet-1.6.0 huggingface_hub-1.32.0 pgmpy-1.1.2 scikit-base-1.1.1
Note: you may need to restart the kernel to use updated packages.

In [34]:
import pandas as pd
df=pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,60,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,35,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,55,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,56,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [35]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import BayesianEstimator
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [37]:
model = DiscreteBayesianNetwork([
 ('age', 'output'), 
 ('sex', 'output'), 
 ('exng', 'output'), 
 ('cp', 'output'), 
 ('output', 'restecg'), 
 ('output', 'chol')
])
estimator = BayesianEstimator(model=model, data=df)
cpds = estimator.get_parameters(prior_type="BDeu", equivalent_sample_size=10)
model.add_cpds(*cpds)
print(model.get_cpds('age'))

C:\Users\HARINI.C\AppData\Local\Temp\ipykernel_21088\1572628500.py:9: FutureWarning: `pgmpy.estimators.BayesianEstimator` is deprecated and will be removed in v1.3.0. Please use `pgmpy.parameter_estimator.DiscreteBayesianEstimator` instead.
  estimator = BayesianEstimator(model=model, data=df)

+---------+------------+
| age(29) | 0.00416021 |
+---------+------------+
| age(34) | 0.00750469 |
+---------+------------+
| age(35) | 0.0175381  |
+---------+------------+
| age(37) | 0.00416021 |
+---------+------------+
| age(38) | 0.0108492  |
+---------+------------+
| age(39) | 0.0141937  |
+---------+------------+
| age(40) | 0.0141937  |
+---------+------------+
| age(41) | 0.0342605  |
+---------+------------+
| age(42) | 0.0275716  |
+---------+------------+
| age(43) | 0.0242271  |
+---------+------------+
| age(44) | 0.0342605  |
+---------+------------+
| age(45) | 0.0275716  |
+---------+------------+
| age(46) | 0.0242271  |
+---------+------------+
| age(47) | 0.0141937  |
+---------+------------+
| age(48) | 0.0242271  |
+---------+------------+
| age(49) | 0.0175381  |
+---------+------------+
| age(50) | 0.0309161  |
+---------+------------+
| age(51) | 0.0409495  |
+---------+------------+
| age(52) | 0.044294   |
+---------+------------+
| age(53) | 0.0309161  |
+---------+------------+
| age(54) | 0.0576719  |
+---------+------------+
| age(55) | 0.037605   |
+---------+------------+
| age(56) | 0.0342605  |
+---------+------------+
| age(57) | 0.0309161  |
+---------+------------+
| age(58) | 0.0543274  |
+---------+------------+
| age(59) | 0.044294   |
+---------+------------+
| age(60) | 0.050983   |
+---------+------------+
| age(61) | 0.0175381  |
+---------+------------+
| age(62) | 0.0342605  |
+---------+------------+
| age(63) | 0.0208826  |
+---------+------------+
| age(64) | 0.037605   |
+---------+------------+
| age(65) | 0.0208826  |
+---------+------------+
| age(66) | 0.0242271  |
+---------+------------+
| age(67) | 0.0275716  |
+---------+------------+
| age(68) | 0.0108492  |
+---------+------------+
| age(69) | 0.0108492  |
+---------+------------+
| age(70) | 0.0141937  |
+---------+------------+
| age(71) | 0.0108492  |
+---------+------------+
| age(74) | 0.00416021 |
+---------+------------+
| age(76) | 0.00416021 |
+---------+------------+
| age(77) | 0.00416021 |
+---------+------------+

In [40]:
print(model.get_cpds('sex'))

+--------+----------+
| sex(0) | 0.327759 |
+--------+----------+
| sex(1) | 0.672241 |
+--------+----------+

In [42]:
print(model.get_cpds('exng'))

+---------+----------+
| exng(0) | 0.675585 |
+---------+----------+
| exng(1) | 0.324415 |
+---------+----------+

In [43]:
print(model.get_cpds('chol'))

+-----------+-----------------------+-----------------------+
| output    | output(0)             | output(1)             |
+-----------+-----------------------+-----------------------+
| chol(126) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(141) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(149) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(157) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(160) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(164) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(166) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(167) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(168) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(172) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(174) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(175) | 0.0002636713600168742 | 0.01784713885554223   |
+-----------+-----------------------+-----------------------+
| chol(177) | 0.015767547329009077  | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(178) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(180) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(182) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(183) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(184) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(185) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(186) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(188) | 0.015767547329009077  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(192) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(193) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(195) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(196) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(197) | 0.008015609344512977  | 0.02372949179671871   |
+-----------+-----------------------+-----------------------+
| chol(198) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(199) | 0.0002636713600168742 | 0.01784713885554223   |
+-----------+-----------------------+-----------------------+
| chol(200) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(201) | 0.0002636713600168742 | 0.01784713885554223   |
+-----------+-----------------------+-----------------------+
| chol(203) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(204) | 0.015767547329009077  | 0.02372949179671871   |
+-----------+-----------------------+-----------------------+
| chol(205) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(206) | 0.015767547329009077  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(207) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(208) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(209) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(210) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(211) | 0.0002636713600168742 | 0.02372949179671871   |
+-----------+-----------------------+-----------------------+
| chol(212) | 0.02351948531350518   | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(213) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(214) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(215) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(216) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(217) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(218) | 0.015767547329009077  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(219) | 0.008015609344512977  | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(220) | 0.0002636713600168742 | 0.01784713885554223   |
+-----------+-----------------------+-----------------------+
| chol(221) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(222) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(223) | 0.008015609344512977  | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(224) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(225) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(226) | 0.0002636713600168742 | 0.02372949179671871   |
+-----------+-----------------------+-----------------------+
| chol(227) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(228) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(229) | 0.02351948531350518   | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(230) | 0.02351948531350518   | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(231) | 0.015767547329009077  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(232) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(233) | 0.008015609344512977  | 0.01784713885554223   |
+-----------+-----------------------+-----------------------+
| chol(234) | 0.015767547329009077  | 0.02372949179671871   |
+-----------+-----------------------+-----------------------+
| chol(235) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(236) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(237) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(239) | 0.015767547329009077  | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(240) | 0.0002636713600168742 | 0.02372949179671871   |
+-----------+-----------------------+-----------------------+
| chol(242) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(243) | 0.015767547329009077  | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(244) | 0.008015609344512977  | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(245) | 0.0002636713600168742 | 0.01784713885554223   |
+-----------+-----------------------+-----------------------+
| chol(246) | 0.015767547329009077  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(247) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(248) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(249) | 0.02351948531350518   | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(250) | 0.0002636713600168742 | 0.01784713885554223   |
+-----------+-----------------------+-----------------------+
| chol(252) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(253) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(254) | 0.03127142329800128   | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(255) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(256) | 0.015767547329009077  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(257) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(258) | 0.015767547329009077  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(259) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(260) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(261) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(262) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(263) | 0.008015609344512977  | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(264) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(265) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(266) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(267) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(268) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(269) | 0.015767547329009077  | 0.01784713885554223   |
+-----------+-----------------------+-----------------------+
| chol(270) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(271) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(273) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(274) | 0.02351948531350518   | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(275) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(276) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(277) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(278) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(281) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(282) | 0.03127142329800128   | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(283) | 0.015767547329009077  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(284) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(286) | 0.015767547329009077  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(288) | 0.015767547329009077  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(289) | 0.015767547329009077  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(290) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(293) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(294) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(295) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(298) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(299) | 0.015767547329009077  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(300) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(302) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(303) | 0.0002636713600168742 | 0.01784713885554223   |
+-----------+-----------------------+-----------------------+
| chol(304) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(305) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(306) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(307) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(308) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(309) | 0.015767547329009077  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(311) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(313) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(315) | 0.008015609344512977  | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(318) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(319) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(321) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(322) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(325) | 0.0002636713600168742 | 0.011964785914365755  |
+-----------+-----------------------+-----------------------+
| chol(326) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(327) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(330) | 0.015767547329009077  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(335) | 0.015767547329009077  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(340) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(341) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(342) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(353) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(354) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(360) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(394) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(407) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(409) | 0.008015609344512977  | 0.0002000800320128053 |
+-----------+-----------------------+-----------------------+
| chol(417) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+
| chol(564) | 0.0002636713600168742 | 0.006082432973189281  |
+-----------+-----------------------+-----------------------+